# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Anatole"
license = "MIT"
licenselink = "https://github.com/lxndrblz/anatole/blob/master/LICENSE"
description = ""
homepage = "https://github.com/lxndrblz/anatole/"
tags = ["blog", "responsive", "clean", "minimalist"]
features = ["blog", "seo", "responsive", "mobile", "disqus"]
min_version = "0.41"

[author]
  name = "Alexander Bilz"
  homepage = "http://alexbilz.com"

# If porting an existing theme
[original]
  name = "Anatole"
  homepage = "http://anatole.cai-cai.me/"
  repo = "https://github.com/hi-caicai/farbox-theme-Anatole"
